### ISSUE TITLE
theme: footer should be fixed to bottom

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#1]
![image](https://user-images.githubusercontent.com/1814661/77409321-558e7c00-6db9-11ea-9cee-0c00d7032987.png)

**Comment by ppanero** [comment]
There is a related issue in `invenio-app-rdm` records. Do you think this could be done as PR there? 👼

**Comment by slint** [comment]
Related to https://github.com/inveniosoftware/invenio-app-rdm/issues/81
