### ISSUE TITLE
migration: search redirections

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#102]
If we compare the [Zenodo search guide](https://help.zenodo.org/guides/search/) and the one that [comes with InvenioRDM](https://inveniordm.web.cern.ch/help/search), there are quite some changes in terms of nested fields (`title` vs `metadata.title`) and semantically equivalent fields (`keyword` vs `subjects`).

Many of these changes are related to the different search index mappings, but also migrated/changed fields. We have to:

- [x] Identify the differences between mappings
- [ ] Make a decision to either...
  - [ ] Use the query parser to translate the fields (see [users example](https://github.com/inveniosoftware/invenio-users-resources/blob/ae6b45e548b554b737b83c6109de4ff4fb14a04a/invenio_users_resources/services/users/config.py#L39-L52))
  - [ ] Use `copy_to` in the mappings to create fields "aliases"; not ideal since it means overriding mappings (which I'm not sure if it's possible atm)

**Comment by alejandromumo** [comment]
Some mappings do not exist anymore, other have changed. I added a small comment on the mappings that are missing:

```python
{
    'access_conditions': 'access',
    'access_right': 'access.*', # access.files, access.embargo.*, access.record, access.status
    'alternate.identifier': 'identifiers.identifier',
    'alternate.scheme': 'identifiers.sheme',
    'communities': 'parent.communities',
    'conceptdoi': '',
    'contributors.\*': 'metadata.contributors.*',
    'contributors.affiliation': 'metadata.contributors.affiliations',
    'contributors.name': 'metadata.contributors.person_or_org.given_name',
    'contributors.orcid': 'metadata.contributors.person_or_org.identifiers', # .identifiers.scheme == 'orcid'
    'contributors.type': 'metadata.contributors.person_or_org.type',
    'created': 'created',
    'creators.\*': 'metadata.creators.*',
    'creators.affiliation': 'metadata.creators.affiliations',
    'creators.name': 'meatadata.creators.person_or_org.given_name',
    'creators.orcid': 'meatadata.creators.person_or_org.identifiers', # .identifiers.scheme == 'orcid'
    'description': 'metadata.description',
    'doi': 'pids.doi.*',
    'embargodate': 'access.embargo.*',
    'filecount': '', # files are under a new link ?
    'filename': '', # files are under a new link  ?
    'filetype': '', # files are under a new link ?
    'grants.\*': 'metadata.funding.*',
    'grants.acronym': 'metadata.funding.award.', # ?
    'grants.code': 'metadata.funding.award.number',
    'grants.funder.\*': 'metadata.funding.funder.*',
    'grants.funder.acronyms': 'metadata.funding.funder.', # ? id?
    'grants.funder.doi': 'metadata.funding', # ?
    'grants.funder.name': 'metadata.funding.funder.name',
    'grants.program': 'metadata.funding.identifiers', # ?
    'grants.title': 'metadata.funding.award.title',
    'imprint.\*': '', # not used anymore ? Seems to be related with "Book/Report/Chapter"
    'imprint.place': '', # not used anymore ? Seems to be related with "Book/Report/Chapter"
    'imprint.publisher': '', # not used anymore ? Seems to be related with "Book/Report/Chapter"
    'isbn': '', # not used anymore ? Seems to be related with "Book/Report/Chapter"
    'journal.\*': '', # not used anymore ? Seems to be related with "Journal"
    'journal.issue': '', # not used anymore ? Seems to be related with "Journal"
    'journal.pages': '', # not used anymore ? Seems to be related with "Journal"
    'journal.title': '', # not used anymore ? Seems to be related with "Journal"
    'journal.volume': '', # not used anymore ? Seems to be related with "Journal"
    'journal.year': '', # not used anymore ? Seems to be related with "Journal"
    'keywords': 'metadata.subject',
    'language': 'metadata.languages', # metadata.languages.id and metadata.languages.title
    'license.\*': 'metadata.rights.*', #
    'license.identifier': 'metadata.rights.id',
    'license.license': 'metadata.rights.title', # ?
    'license.url': 'metadata.rights.props.url',
    'meeting.\*': '', # not used anymore ? seems to be related with "Conference"
    'meeting.acronym': '', # not used anymore ? seems to be related with "Conference"
    'meeting.dates': '', # not used anymore ? seems to be related with "Conference"
    'meeting.place': '', # not used anymore ? seems to be related with "Conference"
    'meeting.session_part': '', # not used anymore ? seems to be related with "Conference"
    'meeting.session': '', # not used anymore ? seems to be related with "Conference"
    'meeting.title': '', # not used anymore ? seems to be related with "Conference"
    'meeting.url': '', # not used anymore ? seems to be related with "Conference"
    'notes': '', # does not exist anymore ?
    'owners': '', # ? creators ?
    'part_of.\*': '', # not used anymore ? seems to be related with "Book"
    'part_of.pages': '', # not used anymore ? seems to be related with "Book"
    'part_of.title': '', # not used anymore ? seems to be related with "Book"
    'publicationdate': 'metadata.publication_date',
    'publication_date': 'metadata.publication_date',
    'recid': 'id',
    'references.\*': '', # not used anymore ? seems to be related with "References"  
    'related.identifier': 'metadata.related_identifiers.identifier',
    'related.scheme': 'metadata.related_identifiers.scheme',
    'related.relation': 'metadata.related_identifiers.relation_type.*',
    'relations.version.count': 'versions.*', # count does not show up anymore ?
    'resource_type.subtype': '', # subtype does not exist anymore ?
    'resource_type.type': 'metadata.resource_type.id',
    'size': '', # files are under a new link?
    'subject.term': '', # subject or keyword?
    'subject.identifier': '', # subject or keyword?
    'title': 'metadata.title',
    'type': 'metadata.resource_type',
    'updated': 'updated',
    'version': 'metadata.version',
    'Resource ': '', # not used anymore ? Did not find any usage in Zenodo, perhaps I am missing something.
}

```

**Comment by alejandromumo** [comment]
Dump can be found at [cernbox](https://cernbox.cern.ch/external/eos/project/d/digital-repositories/Services_Projects/Invenio/RDM/data-migration/zenodo/zenodo-search-redirect-analysis-dump.md?app=CodiMD&fileId=newproject-d%2137572584&contextRouteName=files-spaces-personal&contextRouteParams.item=eos/project/d/digital-repositories/Services_Projects/Invenio/RDM/data-migration/zenodo)

**Comment by zzacharo** [comment]
Extracted missing redirections in https://github.com/zenodo/zenodo-rdm/issues/156

**Comment by slint** [comment]
> "access_conditions", # 'access_conditions' does not exist anymore. It was a description on why the record was restricted. Only availabe for embargoed records.

Agree, the most fitting field would be "embargo reason", but it doesn't match 100%. This has to do with what do we decide about the migration (or not) of the "restricted access" records (i.e. the feature where a user can request access on a closed access record with some conditions).

I would remove it completely and move over to the "failed migrations" so we address later.

> "access_right", # maps to "access.status". However access.status does not work (e.g. query by  'access.status:"open"' yields nothing) and the redirection works (e.g. 'access_right:"open"' yields records).

For the migrated records on ZenodoRDM we don't have many different cases of `access.status`, but the fields mapping is correct.

What needs some tuning is trranslating the **actual search values**:

- (Legacy: RDM)
- `open`: `open`
- `embargoed`: `embargoed`
- `restricted`: `restricted` (this doesn't mean the same though... see the point about `access_condiations`)
- `closed`: `restricted` 👈❗
- N/A: `metadata-only`

Probably that's a new functionality for the query-parser though, since it's about changing with the original search values (not just fields/terms).

> "grants.program", # "metadata.funding.id": validate whether it's the correct mapping

This incorrect, but this information is also not availbale on the metadata of `awards` currently (should be something like `metadata.funding.award.program`).

> "grants.title", # "metadata.funding.award.title.en" : validate whether it's the correct mapping

Yes, that looks correct.

> "grants.funder.acronyms", # "metadata.funding.funder.id" : validate whether it's the correct mapping 

This should be `metadata.funding.award.acronym`, but the field is missing from [the relation configuration](https://github.com/inveniosoftware/invenio-rdm-records/blob/a73e7c3fae65d98999f7fe1ed217a99669361a73/invenio_rdm_records/records/api.py#L117) and [the record mapping](https://github.com/inveniosoftware/invenio-rdm-records/blob/a73e7c3fae65d98999f7fe1ed217a99669361a73/invenio_rdm_records/records/mappings/v7/rdmrecords/records/record-v5.0.0.json#L420).

I'm a bit concerned also that the legacy field is `.acronyms` (plural) and in RDM we have `.acronym` (singular). Probably it's good to assume an array (since it also doesn't make a difference for the mapping).

> "grants.funder.doi", # "metadata.funding.id" : validate whether it's the correct mapping

This one can be `metadata.funding.funder.identifiers.identifier` (since [the funder DOI](https://github.com/inveniosoftware/invenio-vocabularies/blob/21b15c12ed22d7725aa289d0697d5ca1f76af165/invenio_vocabularies/contrib/funders/datastreams.py#L66-L68) is included there).

> "license.license", # "metadata.rights.title.en" : validate whether it's the correct mapping 

Funnily, there is no such field in the actual legacy API mapping 🙃

So no need to map (we should fix that in the legacy search guide).
