### ISSUE TITLE
migration: URL redirections

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#104]

**Comment by kpsherva** [comment]
https://github.com/zenodo/zenodo-rdm/issues/102 I think these are duplicates?

**Comment by slint** [comment]
> #102 I think these are duplicates?

Not really, #102 is about the ES mappings changes, and having to translate some fields to their new names (e.g. `keywords` becomes `subjects` now).  I can clarify a bit more on the issue.

**Comment by alejandromumo** [comment]
Some URLs from Zenodo might not be valid anymore (e.g. got rewritten to something else). In those cases, we need to redirect the old endpoint to the new one. As done here https://github.com/zenodo/zenodo/blob/master/zenodo/modules/redirector/views.py

As a first step, I will list which URLs from `zenodo` do not match in `zenodo-rdm`

**Comment by alejandromumo** [comment]
The list of URLs that do not match in `zenodo-rdm` is the following:

```python
# '/account/settings/github/rejected',
# '/account/settings/github/hook',
# '/beta-features',
# '/sitemap.xml',
# '/account/settings/sharedlinks/static/<path:filename>',
# '/account/settings/github/repository/<path:name>',
# '/account/settings/github/static/<path:filename>',
# '/account/settings/github/hook/<action>/<repo_id>',
# '/account/settings/sessions/revoke',
# '/account/settings/sharedlinks',
# '/account/settings/github',
# '/account/settings/applications/clients/<string:client_id>/reset',
# '/account/settings/sharedlinks/accessrequest/<int:request_id>',
# '/record/<pid_value>/accessrequest/<token>/confirm',
# '/record/<pid(recid,record_class="zenodo.modules.records.api:ZenodoRecord"):pid_value>/admin/delete',
# '/communities/static/<path:filename>',
# '/sitemap<int:page>.xml',
# '/search/static/<path:filename>',
# '/record/static/<path:filename>',
# '/record/<pid(recid,record_class="zenodo.modules.records.api:ZenodoRecord"):pid_value>/registerconceptdoi',
# '/record/<pid_value>/accessrequest',
# '/record/<pid(recid,record_class="zenodo.modules.records.api:ZenodoRecord"):pid_value>/newversion',
# '/badge/latestdoi/<int:user_id>/<path:repo_name>',
# '/badge/latestdoi/<int:github_id>',
# '/badge/static/<path:filename>',
# '/badge/<int:github_id>.svg',
# '/badge/<int:user_id>/<path:repo_name>.svg',

# The following routes can be redirected

'/deposit/<pid_value>',
'/schemas/<path:schema_path>',
'/record/<pid_value>',
'/record/<pid(recid,record_class="zenodo.modules.records.api:ZenodoRecord"):pid_value>',
'/communities/<string:community_id>/curate',
'/communities/<string:community_id>/about',
'/communities/<string:community_id>/edit',
'/record/<pid_value>/preview/<path:filename>',
'/record/<pid_value>/formats',
'/record/<pid_value>/export/<any(csl, hx, xn, schemaorg_jsonld, xm, dcite, '
'ef, json, xd, xe, dcite3, geojson, dcite4, hm, dcat, cp, xw):format>',
'/record/<pid_value>/thumb<thumbnail_size>',
'/record/<pid_value>/files/<path:filename>',
'/communities/<string:community_id>/search',
'/deposit',
'/favicon.ico',
'/deposit/new',

```

**Comment by alejandromumo** [comment]
Migrated routes:
- `/communities/about/<id>/`,
- `/collection/<type>`,
- `/collection/user-<id>`,
- `/communities/<community_id>/curate`,
- `/communities/<community_id>/about`,
- `/communities/<community_id>/edit`,
- `/communities/<community_id>/search`,
- `/dev`,
- `/faq`,
- `/features`,
- `/whatsnew`,
- `/about`,
- `/contact`,
- `/policies`,
- `/privacy-policy`,
- `/terms`,
- `/donate`,
- `/deposit/<pid_value>`,
- `/record/<pid_value>`,
- `/record/<pid_value>/export/<export_format>`,
- `/record/<pid_value>/files/<filename>`,
- `/deposit`,
- `/deposit/new`,
- `/record/<pid_value>/preview/<filename>`,

The following were not migrated yet:

- `/schemas/<path:schema_path>`,
- `/record/<pid_value>/formats`,
- `/record/<pid_value>/thumb<thumbnail_size>`,
