### ISSUE TITLE
create a zenodo-rdm-qa paas instance

### ISSUE THREAD

**Issue by zzacharo** [zenodo/zenodo-rdm#113]
- [ ] spawn QA instance, to have separate testing environment (the sandbox link will become known to the public and we need a stable environment - sandbox - to showcase Zenodo-RDM
- [x] Create a gitlab repo to store the values. See for reference https://gitlab.cern.ch/cds-team/cds-rdm-openshift.
    - Done: https://gitlab.cern.ch/zenodo/zenodo-rdm-openshift
- [ ] Investigate how to properly tag the image to differentiate sandbox from prod deployment.

**Comment by ppanero** [comment]
## Question:

How do we inject `./site` specific configuration. For example:

```
INVENIO_ZENODO_FRONTPAGE_RECENT_UPLOADS_QUERY
INVENIO_ZENODO_RECORDS_UI_CITATIONS_ENDPOINT
INVENIO_ZENODO_RECORDS_UI_CITATIONS_ENABLE
```

**Comment by ppanero** [comment]
Create a split of app config and deployement config, inject app config via helm chart
