### ISSUE TITLE
ui: missing GitHub/ORCiD option in sign-up page

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#116]
Legacy:

![image](https://user-images.githubusercontent.com/1814661/204338076-7eb23276-345c-4716-b716-ec9204ec2ca3.png)

RDM:

![image](https://user-images.githubusercontent.com/1814661/204338148-5690a191-de86-479f-89ba-4c0eff452c6e.png)

**Comment by alejandromumo** [comment]
Screenshot: 
![image](https://user-images.githubusercontent.com/21204744/205060037-fcf9bd27-0842-4017-9715-d0ba562848fa.png)

**Comment by alejandromumo** [comment]
screenshot:

![image](https://user-images.githubusercontent.com/21204744/205067271-960c0282-513c-4c4f-8b5e-09d12cfcb594.png)
