### ISSUE TITLE
ui: record landing page details sidebar titles font style

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#122]
I think these should be bold/strong or similar:

ZenodoRDM:

![Image](https://user-images.githubusercontent.com/1814661/205074083-02148f34-4158-473a-8a35-d70994914c0c.png)

vs. 

InvenioRDM:

![Image](https://user-images.githubusercontent.com/1814661/205074244-9c5c704a-c703-4bd9-8a33-580a6de5fd51.png)

**Comment by Pineirin** [comment]
Couldn't reproduce.
![Screenshot from 2022-12-02 17-35-51](https://user-images.githubusercontent.com/25476209/205341069-ec63f12c-bb18-4771-82be-c95da6bccd96.png)
