### ISSUE TITLE
legacy API: migrate remaining routes

### ISSUE THREAD

**Issue by alejandromumo** [zenodo/zenodo-rdm#146]
When the routes were being migrated in #104 , three of them were not found an equivalent.

In task, it should be evaluated whether they have a correspondant in RDM or are simply gone. 

- [ ] `/schemas/<path:schema_path>`, 
  - Serve legacy schema as static file.
- `/record/<pid_value>/formats`, **planned for the MS6 milestone**
- `/record/<pid_value>/thumb<thumbnail_size>`, **planned for the MS6 milestone**

If they do have equivalents in RDM, they must be migrated in this task (see #104 on how others were migrated).

**Comment by zzacharo** [comment]
@slint Serve the new internal jsonschema file you mean? Or the legacy one? The latter I guess it doesn't make sense no? Or people can still use it as we will have the legacy API for that?

**Comment by slint** [comment]
To serve the legacy JSONSchema file as static, since it's still a way to pre-validate JSON before sending it to the Legacy REST API.
