### ISSUE TITLE
deployment: re-deploy zenodo-rdm with a newer image

### ISSUE THREAD

**Issue by alejandromumo** [zenodo/zenodo-rdm#170]
Signup options (e.g. `auto_confirm`) were added in `invenio_oauthclient == v2.1.0`. 

- `zenodo-rdm` does not have this change (currently deployed `prod` image has `invenio_oauthclient == 2.0.1`)
- `zenodo-rdm-qa` already has this change, as the image is fetched from `latest` 

This is particularly relevant for Github login, as the users should be auto confirmed when registering via Github account.

**Comment by zzacharo** [comment]
`v0.2.0` deployed https://github.com/zenodo/zenodo-rdm/tree/v0.2.0
