### ISSUE TITLE
Migrator module fails in tests

### ISSUE THREAD

**Issue by alejandromumo** [zenodo/zenodo-rdm#173]
Running `python -m pytest` (without specifying the `tests/` folder) fails with the following error: 

```
ERROR zenodo_rdm/migrator/dump_communities.py - RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.
ERROR zenodo_rdm/migrator/extract.py - ModuleNotFoundError: No module named 'psycopg'
ERROR zenodo_rdm/migrator/stream.py - ModuleNotFoundError: No module named 'invenio_rdm_migrator'
ERROR zenodo_rdm/migrator/transform.py - ModuleNotFoundError: No module named 'invenio_rdm_migrator'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

The first error is raised here: 

https://github.com/zenodo/zenodo-rdm/blob/master/site/zenodo_rdm/migrator/dump_communities.py#L4

The later ones seem to be related with missing dependencies.

Note that running `python -m pytest tests/` works as indended and tests pass.

This error blocked the addition of a Github task to automatically run tests. See more details in https://github.com/zenodo/zenodo-rdm/pull/171#issuecomment-1380459963

**Comment by ppanero** [comment]
I think pytest is trying to load code without an app fixture.

**Comment by zzacharo** [comment]
I think I will add invenio-rdm-migrator in the Pipfile as it was missing and that will solve the issue.

**Comment by alejandromumo** [comment]
I pulled from master and it is not failing anymore. Therefore I will close this issue.

Thank you guys!
