### ISSUE TITLE
Gather extensive list of requests from LORY

### ISSUE THREAD

**Issue by kpsherva** [zenodo/zenodo-rdm#179]
Community in Zenodo: https://zenodo.org/communities/lory

**Comment by alejandromumo** [comment]
## LORY analysis

- LORY does not have any specific integration / workflow implemented in our side (Zenodo).
- They rely on the Zenodo API to upload records. Therefore, we must guarantee that RDM API is compatible with their usage of the current Zenodo API (e.g. endpoints calls, search queries - if any)
- We should contact them at some point. In the meantime, I analysed which type of records they have and which type of endpoint calls they're using (through access logs).

## Records

I retrieved all the communities of LORY and analysed all the records belonging to such communities.

```
TOTAL = 333 total records

field name                 non-empty values
alternate_identifiers        4
communities                333
conceptdoi                 243
conceptrecid               333
contributors                21
creators                   333
description                333
doi                        333
embargo_date                11
filecount                  326
imprint                    137
journal                    141
keywords                   120
language                    49
license                    330
meeting                     18
notes                      259
owners                     333
part_of                     74
provisional_communities    329
publication_date           333
recid                      333
related_identifiers        257
relations                  333
resource_type              333
size                       326
subjects                    42
thesis                      35
title                      333
version                      5
```

Some fields e.g. `journal`, `meeting`, `imprint`, `notes`, `thesis`, `provisional_communities` are not supported yet in RDM. These terms were not migrated in https://github.com/zenodo/zenodo-rdm/issues/102


## Endpoint calls

WIP

**Comment by kpsherva** [comment]
closing as agreed with @slint
