### ISSUE TITLE
legacy: implement fields that require porting in InvenioRDM

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#187]
> NOTE: This can be split up into smaller issues as well to implement groups of fields as we progress through milestones

- [ ] `access_conditions`
- [x] `notes`
- [x] `references`
- [ ] `communities`
- [x] `journal_title`
- [x] `journal_volume`
- [x] `journal_issue`
- [x] `journal_pages`
- [x] `conference_title`
- [x] `conference_acronym`
- [x] `conference_dates`
- [x] `conference_place`
- [x] `conference_url`
- [x] `conference_session`
- [x] `conference_session_part`
- [x] `imprint_publisher`
- [x] `imprint_isbn`
- [x] `imprint_place`
- [x] `partof_title`
- [x] `partof_pages`
- [x] `thesis_supervisors`
- [x] `thesis_university`
- [x] `locations`
- [x] `dates`
- [x] `languages`
- [x] `method`
- [x] `related_identifiers`
- [x] `version`   
- [x] `access_rights`
- [x] `embargo_date`

**Comment by alejandromumo** [comment]
Missing fields:


```
- access_right     (doable now, however RDM has the format of 'record', 'files' and 'embargo' and each one 
- embargo_date     (only applies to embargoed)
- access_conditions     (only applies to restricted access records)
- doi    
- prereserve_doi   
- communities     (RDM has parent.communities or parent.review.communities)
- subjects    (needs a strategy to be defined first)
```

**Comment by zzacharo** [comment]
`communities` should be probably be coordinated with `draft.communities` during migration so they share the same logic of either creating an inclusion request i.e `parent.review` or marking them as part of the draft i.e storing them in `parent.communities`.

**Comment by slint** [comment]
`communities` field support split to https://github.com/zenodo/zenodo-rdm/issues/346
