### ISSUE TITLE
Data migration: All custom fields (Darwin Core)

### ISSUE THREAD

**Issue by kpsherva** [zenodo/zenodo-rdm#245]

**Comment by ppanero** [comment]
@kpsherva isn't this done? https://github.com/zenodo/zenodo-rdm/pull/234/files#diff-4000189d4e8a64701293311ec9e50e84f3a070ba9798626b9f0f26de80bf4629R141

**Comment by ppanero** [comment]
Discuss IRL, TBChecked but is done

**Comment by zzacharo** [comment]
@slint  can you double check that all fields are mirgated so we can close this one?

**Comment by ppanero** [comment]
@alejandromumo it was in review because it needs crosschecking that all the fields were migrated.
