### ISSUE TITLE
search mapping `size` and `sizes`

### ISSUE THREAD

**Issue by ppanero** [zenodo/zenodo-rdm#268]
The first is backwards compatible to Zenodo.org and it refers to file sizes, the second refers to the new metadata field. Should we keep both? they can be confusing, maybe prefix the first with "file"?

**Comment by slint** [comment]
We have to keep the compatibility for the old API in any case, so we need a query alias/transformer. 

On another note, could we nest the fields, e.g. like `files.size`? Or is `files` an array of objects already?
