### ISSUE TITLE
legacy api: community creation

### ISSUE THREAD

**Issue by kpsherva** [zenodo/zenodo-rdm#296]

**Comment by alejandromumo** [comment]
I did not find an endpoint to create communities in the legacy API.

Nonetheless, spoke irl and concluded that the endpoints that we should migrate are the ones available in developers.zenodo.org . Namely:

- https://developers.zenodo.org/#depositions

Less urgent:
- https://developers.zenodo.org/#records
- https://developers.zenodo.org/#licenses

Communities endpoints are not listed in the linked docs
