### ISSUE TITLE
migration: production db inconsistencies

### ISSUE THREAD

**Issue by ppanero** [zenodo/zenodo-rdm#344]
- [x] Multiple Object versions with `is_head = true` (cleaned "manually" with an SQL query)
- [x] Duplicate Object version IDs `032b5cb7-735e-41a9-9291-e4304e8f67a2` (probably from when we had the DB incident)
- [x] `_files` are not consistent with the buckets/OVs/file state

Additionally, there's a duplicate DOI issue, tracked on a Zenodo private repo, on issue `#301` (backlinked for Zenodo team to be able to follow the link)

**Comment by slint** [comment]
Solved on production data and via #408.
