### ISSUE TITLE
migrator: integrate awards/funder loading in streams

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#356]
Integrate awards/funders CSV dumps loading In the regular migrator streams via the `existing_data: true` flag.

_Originally posted by @slint in https://github.com/zenodo/zenodo-rdm/pull/351#discussion_r1201879404_

**Comment by zzacharo** [comment]
already implemented https://github.com/zenodo/zenodo-rdm/commit/1c62db4d2ec712c8c48ffb543d6492f3a081c69b
