### ISSUE TITLE
theming: community details

### ISSUE THREAD

**Issue by kpsherva** [zenodo/zenodo-rdm#49]
<img width="1262" alt="Screenshot 2022-10-11 at 13 15 35" src="https://user-images.githubusercontent.com/38131488/195076081-47d4d63a-9a20-449c-a9c2-bb51e6e3ea3a.png">

# Preparation
- [ ] make sure the layout is defined
- [ ] gather all the additional information about changes/decisions regarding the elements of the frontpage (fill the `#decisions` section below)
- [ ] define elements which need changes

# Elements to customise

TBD

# Decisions

TBD

Postponed as the layout needs a bigger discussion.

**Comment by jennur** [comment]
Replaced by https://github.com/inveniosoftware/invenio-communities/issues/867
