### ISSUE TITLE
infra: update configuration for the different environments

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#524]
We currently have a bit of a mix/conflict between configuration sources:

- this repo's `invenio.cfg`
- GitLab repository with OpenShift Helm charts values: https://gitlab.cern.ch/zenodo/zenodo-rdm-openshift/
- What is actually the deployed/live config on the various OpenShift projects (ConfigMaps and Secrets)

Given that multiple new features require specialized secrets/config (https://github.com/zenodo/zenodo-rdm/pull/500, https://github.com/zenodo/zenodo-rdm/pull/522, OpenAIRE direct indexing), we should take the chance to reconcile all these config sources.

Some important notes:

- Application config (available even in local development) should be only in `invenio.cfg` (or even in upstream modules if it makes sense IvnenioRDM-wide). One such example is the `GITHUB_WEBHOOK_RECEIVER_ID = 'gtihub'` (we would never use a different value in dev/prod/QA).
- Ideally, we should always aim at using `helm upgrade` (or similar) to apply any configuration changes to the deployed environments
- Synchronize with @psaiz as well for changes to the GitLab repo, since there is some ongoing parallel work on OpenShift infra at the moment

**Comment by alejandromumo** [comment]
I've found that the following configs could be removed from openshift:

- `GITHUB_WEBHOOK_RECEIVER_ID`  (removed from zenodo-rdm-openshift, it's added by the module and should work)
- `GITHUB_INTEGRATION_ENABLED` (removed from zenodo-rdm-openshift, already exists in zenodo_rdm/invenio.cfg)
- `DATACITE_ENABLED` (removed from zenodo-rdm-openshift, already exists in zenodo_rdm/invenio.cfg)
- `DATACITE_PREFIX` (removed from zenodo-rdm-openshift, already exists in zenodo_rdm/invenio.cfg)
- `GITHUB_RELEASE_CLASS` (removed from openshift, already in invenio.cfg and added a default in invenio-app-rdm)
- `MAIL_DEFAULT_SENDER` (removed from openshift, moved to invenio.cfg)
- `ZENODO_RECORDS_UI_CITATIONS_ENDPOINT` (removed from openshift, already in zenodo_rdm/config.py)
