### ISSUE TITLE
community details: make sure all demo data fields look pretty on the page

### ISSUE THREAD

**Issue by anikachurilova** [zenodo/zenodo-rdm#65]
Make sure the `description`, `curation_policy` and `page` fields on community details page are visible.
Currently, the `communities.yaml` file consists of plain text for these fields ([see the comment](https://github.com/zenodo/zenodo-rdm/pull/64/files#r1001780247))

Steps to be done:
- show all the fields on the page (currently only the `description` is visible)
- fix/create(?) the html parsing for yaml file at the community details page
- replace the plain text in `description`, `curation_policy` and `page` fields in `community.yaml` file with the original html script.

See links to copy-paste the original htmls from (in the same order as in the file):
- https://zenodo.org/api/communities/biosyslit
- https://zenodo.org/api/communities/cernopenlab
- https://zenodo.org/api/communities/linguistics
- https://zenodo.org/api/communities/aas
- https://zenodo.org/api/communities/astrothesis
- https://zenodo.org/api/communities/briefideas
- https://zenodo.org/api/communities/ecfunded
- https://zenodo.org/api/communities/lara
- https://zenodo.org/api/communities/tops
- https://zenodo.org/api/communities/cs19
- https://zenodo.org/api/communities/covid-19
- https://zenodo.org/api/communities/wind_energy

**Comment by ppanero** [comment]
@anikachurilova @zzacharo @slint is this issue part of the sprint? should it be added to the board?

**Comment by zzacharo** [comment]
I think there is an issue already, but I don't think we will work on communities details page on this sprint!

**Comment by kpsherva** [comment]
@zzacharo it is part of the theming, why is it not part of the sprint ?

**Comment by zzacharo** [comment]
The communities detail page, if I remember correctly, will be redesigned in the future implementing a community identity feature. For this milestone, I don't remember having as a task to implement missing information from the community details page in RDM....
