### ISSUE TITLE
deposit form: evaluate resource types

### ISSUE THREAD

**Issue by kpsherva** [zenodo/zenodo-rdm#69]
are the resource types available in invenio-rdm suitable for the demo site ?

**Comment by slint** [comment]
Yes, they are fine for now. 

Once we approach data migration we'll have to revisit and update the [default resource types in `invenio-rdm-records` ](https://github.com/inveniosoftware/invenio-rdm-records/blob/eaf81df9f557083c52297b78324af56f27ae0c93/tests/fixtures/data/vocabularies/resource_types.yaml) using the current [resource types in Zenodo](https://github.com/zenodo/zenodo/blob/0745123059237a26dae20332b6ccb4800191254a/zenodo/modules/records/data/objecttypes.json). This might also mean data migration for the current InvenioRDM instances.

**Comment by slint** [comment]
I've also opened https://github.com/inveniosoftware/invenio-rdm-records/pull/1118 to add the missing types to the upstream repo in case we want to synchronize them in the future.
