### ISSUE TITLE
Recent Uploads Section

### ISSUE THREAD

**Issue by kpsherva** [zenodo/zenodo-rdm#690]
![image](https://github.com/zenodo/zenodo-rdm/assets/6676843/cf84c15a-3b5d-493d-a5ff-9623faae36ef)

- [x] Show three most recent records
- [ ] Show the communities that it is present in

For some reason the PR won't link https://github.com/inveniosoftware/invenio-communities/pull/1087

**Comment by carlinmack** [comment]
Commits are in https://github.com/inveniosoftware/invenio-communities/tree/feature/ec-frontpage. Screenshots:


![Image](https://github.com/zenodo/zenodo-rdm/assets/6676843/0413d187-4a62-400e-bf77-27692ea96c65)

![Image](https://github.com/zenodo/zenodo-rdm/assets/6676843/665cb150-42a1-4f41-9d61-8441e13ce1b6)

![Image](https://github.com/zenodo/zenodo-rdm/assets/6676843/2c1f7b00-920a-41fc-a8af-4490396eabcf)
