### ISSUE TITLE
Join Waiting List (To add a community as a EC project)

### ISSUE THREAD

**Issue by kpsherva** [zenodo/zenodo-rdm#692]
![Image](https://github.com/zenodo/zenodo-rdm/assets/51617644/21eec88c-e855-4313-8656-5756e033f557)

**Comment by kpsherva** [comment]
link the button to a static page, not a support form

**Comment by alejandromumo** [comment]
https://github.com/zenodo/zenodo-rdm/pull/724 already reviewed in https://github.com/zenodo/zenodo-rdm/issues/706
