### ISSUE TITLE
Import EuroSciVoc vocabulary fixtures in QA

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#772]

**Comment by alejandromumo** [comment]
The vocabulary is now in QA: https://sandbox.zenodo.org/api/subjects

Used in one community: 
https://sandbox.zenodo.org/communities/test_community_lorozco/settings


I noticed that the vocabulary was not capitalized and there is a bug in the fixtures loading that wasn't addressed so far:

https://github.com/inveniosoftware/invenio-rdm-records/pull/1686
https://github.com/zenodo/zenodo-rdm/pull/773

I can manually import the vocabulary in prod but these two should be merged for other instances

**Comment by alejandromumo** [comment]
Imported in QA and prod
