### ISSUE TITLE
configure github and orcid login

### ISSUE THREAD

**Issue by kpsherva** [zenodo/zenodo-rdm#78]

**Comment by alejandromumo** [comment]
## Orcid 
Orcid is currently not configured in zenodo-rdm. 


## Github
It is working, however with some issues:

- If the Github's account email is already associated to an invenio account, it fails to login.
- After logging in, a confirmation e-mail is sent to the user. A login page is shown again to the user. After confirmation, the login from Github works as intended.
- During the first login, the account does not show up as linked to a Github account.

To do in this issue:
- Automatically register and confirm an user that is logged in from Github
- Link the Github account to the user after the first login. 
- If an account already exists with the same e-mail: ???
