### ISSUE TITLE
What are the acceptable formats that we convert to tiled images (PNG, JPG, TIF, PDF?)

### ISSUE THREAD

**Issue by 0einstein0** [zenodo/zenodo-rdm#820]
| Format | Pyvips → .tif |
| --- | --- |
| JPEG | Y |
| JP2 | Y |
| PNG | Y |
| GIF | N |
| TIFF* | Y |
| BMP | Y |
| RAW | Y |
| SVG | N |
| EPS | N |
| PDF* | Y |
| WEBP | Y |
| HEIF | Y |
| DCM | N |

**Comment by ptamarit** [comment]
* For multi-layered TIFFs as input, pyvips discards the next layers.
* For PDFs, pyvips could generate a thumbnail of the first page.
