### ISSUE TITLE
Run pyramidal TIFF image tile generation over a good sample of images from Zenodo production, to determine good set of parameters (compression quality, etc.)

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#825]
TEST

Input Folder: 1.08 GB

Number of Files: 30

- Q=90, compression='jpeg', tile_width=256
- Output Folder: 2.77 GB
- Conversion completed in 47.34 seconds.
##
- Q=90, compression='jpeg', tile_width=512
- Conversion completed in 44.69 seconds.
- Output: 2.76
##
- Q=90, compression='lzw', tile_width=256
- Conversion completed in 201.40 seconds.
- Output: 8.25 GB

##
- Q=80, compression='jpeg', tile_width=256
- Conversion completed in 40.88 seconds.
- Output: ~700MB
##

To test further
| Q      | Compression | tile size | Output Folder | Conversion Time 
| ------ | -------- | ------- | ----------- | ----------------- |
| **90** | **jpeg** | **256** | **2.77 GB** | **47.34 seconds** |

| Region Shrink | Conversion Time |
| ------------- | --------------- |
| Nearest       | 38.44 seconds   |
| Max             | 42.42           |
| Median              |    42.25             |

**Comment by yashlamba** [comment]
Closing as done in previous sprint.
