### ISSUE TITLE
Backend: add support for subcommunity request in RDM

### ISSUE THREAD

**Issue by carlinmack** [zenodo/zenodo-rdm#867]
The goal is to have a first version of the functionality ready for RDM. It contains:

- A new request type 
- A new resource to support the creation of the request
- A new service to work the data and create the request. 

The RFC already contains an updated prototype for these

**Comment by alejandromumo** [comment]
Moved the issue to invenio-communities: https://github.com/inveniosoftware/invenio-communities/issues/1147
