### ISSUE TITLE
Integrate the MeSH vocabulary

### ISSUE THREAD

**Issue by jrcastro2** [zenodo/zenodo-rdm#926]
Importing using [galterlibrary/invenio-subjects-mesh](https://github.com/galterlibrary/invenio-subjects-mesh)

**Comment by yashlamba** [comment]
3 proposals to fetch MeSH:
- PyPI as storage and use PyPI api to see if we have a new release since the last import
- Publish `invenio-subjects-mesh` on Zenodo and fetch it like ROR
- Publish as asset on GitHub release of `invenio-subjects-mesh`
