### ISSUE TITLE
export formats: add swhid to datacite, bibtex, codemeta, cff (don't trigger metadata-only deposit when only swhid was added)

### ISSUE THREAD

**Issue by alejandromumo** [zenodo/zenodo-rdm#936]
Add swhid to serializers, taking into account that the module installation on a RDM instance is optional

**Comment by santolucito** [comment]
will this let us generate bibtex citations for artifacts through the web interface?

**Comment by alejandromumo** [comment]
> will this let us generate bibtex citations for artifacts through the web interface?

I'm sorry, I did not fully understand the question.

This development will export the Software Heritage ID to different formats. It's already possible to generate BibTex citations from the web interface. 

For further questions please contact Zenodo on support: https://zenodo.org/support
