### ISSUE TITLE
issues with adding external email as owner of community 

### ISSUE THREAD

**Issue by nicolevasilevsky** [zenodo/zenodo-rdm#945]
Hi- I am the owner of this zenodo community: https://zenodo.org/communities/isb/members?q=&l=list&p=1&s=25&sort=name

and I want to make this email account an owner:
intsocbio at gmail dot com

The account should be public but I am unable to invite them as a member to the community:

![image](https://github.com/user-attachments/assets/b0ce8937-97e8-4765-8568-b8af07d4e437)

Thanks for any help!

cc @sbello

**Comment by carlinmack** [comment]
Hi Nicole, I'm glad to see that you have since been able to add this user as an owner of your community

Thank you for the bug report, we are actively working on improving search and this is a good example for us to improve on

**Comment by nicolevasilevsky** [comment]
Thank you!
