### ISSUE TITLE
Implement rate-limiting for User-Agents to unblock `Googlebot`

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#950]

**Comment by alejandromumo** [comment]
I believe this can be closed now that we changed the strategy of the rate limiting to NGINX, WDYT @slint ?

**Comment by slint** [comment]
Yes, this has been implemented on the nginx level, so we're good to close

**Comment by zzacharo** [comment]
> Yes, this has been implemented on the nginx level, so we're good to close

do you have a link pointing to the applied code on nginx level?

**Comment by slint** [comment]
@zzacharo opened https://github.com/zenodo/zenodo-rdm/pull/983, which contains that nginx config :)
