### ISSUE TITLE
Sync with Github error (Request failed with status code: 504)

### ISSUE THREAD

**Issue by AliciaMstt** [zenodo/zenodo-rdm#957]
Hi,

I'm trying to sync a github repo from an organization (of which I'm the onwer) with my Zenodo. This is something I have done before with other organization, but the problem is with a new one. I have enabled third-party access to the Zenodo application, however my new organization's repositories do not show up in the list. 

I think the problem is that my list of repos was updated 10 months ago, and the organization and repo I want to add are new.

<img width="946" alt="image" src="https://github.com/zenodo/zenodo/assets/5412404/e9a5c2d6-b1ec-41d5-945e-cbbec5747846">

However, when I click "Sync now" after few seconds I'm getting the error Request failed with status code: 504

<img width="948" alt="image" src="https://github.com/zenodo/zenodo/assets/5412404/10d7711c-1b22-49f4-a015-ff85e7457157">

My internet connection is stable and of 17 Mbps. Is there a gateway timeout problem from your side? Or what can I do? I'm having this problem since yesterday and it is starting to become urgent.

This issue is related to https://github.com/zenodo/zenodo/issues/1814 but since I think the problem is with the sync, I opened a new issue instead of reporting it in that thread. 

Thanks!

**Comment by zimolzak** [comment]
Update: I checked today, and now Zenodo reports that a successful sync of my GitHub repos happened 3 days ago. However, if I try to request sync again, I get the same error. (I only tried once today, though.)

I got the repo I wanted, so that's good, I guess? But the problem seems to be persisting. 🤷

**Comment by blakeNaccarato** [comment]
What worked for me was to go to "Linked accounts" in the left sidebar just above the "GitHub" menu we are currently in , then click "Disconnect" on the "GitHub" option, then click "Connect" again. Upon returning to the prior menu it says "updated now" (unless that coincidentally went through from a prior click of sync).

**Comment by peterdudfield** [comment]
+1 happening to me when I added an new organisation

**Comment by priya-gitTest** [comment]
+1

**Comment by joshmoore** [comment]
> Just realized that you will have to click the "On" switch again for any repo you previously synced with Zenodo!

This sounds very daunting. I will reply on the email and see if this issue can be re-opened.

**Comment by thawn** [comment]
@joshmoore I agree that re-connecting is not an ideal solution. Any news regarding your email?

**Comment by e-kotov** [comment]
> What worked for me was to go to "Linked accounts" in the left sidebar just above the "GitHub" menu we are currently in , then click "Disconnect" on the "GitHub" option, then click "Connect" again. Upon returning to the prior menu it says "updated now" (unless that coincidentally went through from a prior click of sync).

same here, only this worked for me.

**Comment by joshmoore** [comment]
@thawn: new news though I had pinged them about this thread and said:

> The experience is apparently that then individual repositories must be reactivated. That would not be an option for me.

**Comment by joshmoore** [comment]
I'm going to try creating a new issue and see if that will be seen: https://github.com/zenodo/zenodo-rdm/issues/1107  Please join me there.

**Comment by richelbilderbeek** [comment]
Same here again. Directly after clicking on sync, the server crashed ... :-/ . Unsure if it was due to that...

When the server came back up, I still cannot sync.

**Comment by joshmoore** [comment]
We have all now moved to https://github.com/zenodo/zenodo-rdm/issues/1118 if you'd like to join us!
