### ISSUE TITLE
Subjects vocabulary hierarchical metadata ingestion

### ISSUE THREAD

**Issue by alejandromumo** [zenodo/zenodo-rdm#986]
The vocabulary EuroSciVoc needs to store the parent information for each term. Example:

```terminal
Natural Sciences 
|
| --- Mathematics
```

This information should be stored in DB

**Tasks**:

- Update euroscivoc to include parent information
- Update ids to use notation instead of uri
- Store uri as separate identifiers

Download from here: https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/euroscivoc

**Comment by 0einstein0** [comment]
- Update euroscivoc to include parent information
- Update ids to use notation instead of uri
- Store uri as separate identifiers

Download from here: https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/euroscivoc
